#!/bin/sh
#
# resize - resize focused window in a given direction

case $1 in
    east)  dim=w; dir=right; falldir=left;   sign=+;;
    west)  dim=w; dir=right; falldir=left;   sign=-;;
    north) dim=h; dir=top;   falldir=bottom; sign=-;;
    south) dim=h; dir=top;   falldir=bottom; sign=+
esac

case $dim in
    w) x=$sign"10"; y=0;;
    h) y=$sign"10"; x=0
esac

# try to resize in one direction
# fall back to the other if it fails
bspc node -z "$dir" "$x" "$y" || bspc node -z "$falldir" "$x" "$y"
