#!/bin/bash
sleep 5
DISPLAY=:0
XAUTHORITY=/run/user/1000/Xauthority
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

export DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS

lista=`xinput list | grep -i 'mouse'`
listb=`xinput list | grep -i 'transceiver' | grep -i 'pointer'`
listc=`xinput list | grep -i 'receiver' | grep -i 'pointer'`

ID=`xinput list | grep -Eio 'touchpad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`

if [ ${#lista} -eq 0 ] && [ ${#listb} -eq 0 ] && [ ${#listc} -eq 0 ]; then
    xinput enable $ID
    dunstify 'No USB Mouse Detected' "Your Touchpad is Active"
else
    xinput disable $ID
    dunstify "USB Mouse Detected" "Your Touchpad is Disabled"
fi

