#!/bin/bash
#bspc monitor -g 1920x1080+0+0
SCRIPTS="$HOME/.config/bspwm/scripts"

# get workspaces according to q-ty of monitors
$SCRIPTS/bspwm_monitors
# get monitor dimensions for mpv, tmux and other scratches))
. $SCRIPTS/bspwm_dimensions

# Autostart
polybar_launch &					# simple customizeble bar
setbg &								# set wallpaper form script
mousedetect &						# Turn off touchpad. run once
picom --experimental-backend &		# start compositor
$SCRIPTS/conky_start &				# conky clock

bspc config remove_unplugged_monitors true

### Colors
. $SCRIPTS/bspwm_color

bspc config border_width			2
bspc config normal_border_color		"$color8"
bspc config active_border_color		"$color7"
bspc config focused_border_color	"$color6"
bspc config presel_feedback_color	"$color0"

bspc config  window_gap		4
bspc config  top_padding	8
bspc config  bottom_padding	8
bspc config  left_padding   2
bspc config  right_padding  2

bspc config automatic_scheme      alternate
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true
bspc config focus_follows_pointer false
bspc config pointer_modifier 	  control

### Apps and windows
###############################################
#bscp rule -a polybar manage=off

# Rules
# Scratches
bspc rule -a scratch_fm sticky=on state=floating rectangle=1400x800+0+0 center=on
bspc rule -a scratch_ncmpcpp sticky=on state=floating rectangle="$newwidth"x"$newheight"+"$hor"+"$vert"
bspc rule -a scratch_pulse sticky=on state=floating rectangle=1000x300+0+0 center=on
bspc rule -a scratch_term sticky=on state=floating rectangle="$tmuxwidth"x"$newheight"+"$offset"+"$tmuxvert"
bspc rule -a scratch_btm desktop='^10' follow=on
# Normal rules

bspc rule -a KotatogramDesktop desktop='^5'
bspc rule -a Zathura state=tiled follow=on

bspc rule -a Steam desktop='^9'
bspc rule -a Lutris desktop='^9'
bspc rule -a Arandr state=floating rectangle=800x600+0+0 center=on
bspc rule -a Pavucontrol state=floating rectangle=800x600+0+0 center=on
bspc rule -a SimpleScreenRecorder  state=floating
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating sticky=on rectangle="$newwidth"x"$newheight"+"$hor"+"$vert"
bspc rule -a Qalculate-gtk state=floating center=on
bspc rule -a Gsimplecal  rectangle=340x270+790+40
bspc rule -a epicgameslauncher.exe  desktop='^8' state=tiled
bspc rule -a term_nmtui state=floating center=on rectangle=700x470+0+0

bspc rule -a ts-polkitagent state=floating center=on rectangle=700x470+0+0
bspc rule -a Pcmanfm state=floating center=on

# zenity file choser dialog fix
bspc rule -a "File Upload" state=floating center=on
bspc rule -a "Choose Files" state=floating center=on
bspc rule -a '*:Select file' state=floating center=on

# office
#bspc rule -a '*:soffice' desktop='^7'

# External
bspc config external_rules_command  $HOME/.local/bin/bspwm/ext_rules



