#!/bin/bash
# rule example:
# bspc rule -a mpv state=floating sticky=on rectangle="$newwidth"x"$newheight"+"$hor"+"$vert"
# and add next line to bspwmrc. POINT is important!
# . ~/.config/bspwm/bspwm_mpv
offset=7 # this is offset to show window border. just for fun

monwidth=$(xdotool getdisplaygeometry | awk '{print $1}')
monheight=$(xdotool getdisplaygeometry | awk '{print $2}')

newwidth=$((monwidth / 3))
newheight=$((monheight / 3))
hor=$((monwidth - newwidth - offset)) \
vert=$((monheight - newheight - offset))

tmuxwidth=$((monwidth - 2 * offset))
tmuxvert=$((2 * newheight - offset))
