#!/bin/bash
sxhkd &
bspc monitor -g 1920x1080+0+0
xsetroot -cursor_name left_ptr &
setbg &

$HOME/.config/bspwm/bspwm_monitors
$HOME/.config/polybar/launch.sh

#get monitor dimensions for mpv, tmux and other scratches))
. ~/.config/bspwm/bspwm_dimensions

bspc config remove_unplugged_monitors true

### Colors

. "${HOME}/.config/bspwm/color"

bspc config border_width         2
bspc config normal_border_color "$color8"
bspc config active_border_color "$color7"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color0"

for SPACE in $SPACES
do
  bspc config -d ${SPACE} window_gap      10
  bspc config -d ${SPACE} top_padding     8
  bspc config -d ${SPACE} bottom_padding  10
  bspc config -d ${SPACE} left_padding   10
  bspc config -d ${SPACE} right_padding  10
done

bspc config automatic_scheme      alternate
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true
bspc config focus_follows_pointer false
bspc config pointer_modifier 	  control

### Apps and windows
###############################################
#bscp rule -a polybar manage=off

# Rules
bspc rule -a scratch_vifm sticky=on state=floating rectangle=1400x800+0+0 center on
bspc rule -a scratch_pulse sticky=on state=floating rectangle=1000x300+0+0 center on
bspc rule -a scratch_bc sticky=on state=floating rectangle=1000x300+0+0 center on
bspc rule -a scratch_tmux sticky=on state=floating rectangle="$tmuxwidth"x"$newheight"+"$offset"+"$tmuxvert"

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a firefox:Toolkit state=floating sticky=on rectangle="$newwidth"x"$newheight"+"$hor"+"$vert"
bspc rule -a Doublecmd desktop='^4'
bspc rule -a KotatogramDesktop desktop='^5'
bspc rule -a Gimp desktop='^6'
bspc rule -a Zathura desktop='^7' state=tiled follow=on
bspc rule -a '*:libreoffice' desktop='^8' state=tiled
bspc rule -a '*:soffice' desktop='^8'
bspc rule -a Steam desktop='^9'
bspc rule -a Lutris desktop='^9'
bspc rule -a "VirtualBox Manager" desktop='^10'
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Arandr state=floating rectangle=800x600+0+0 center=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a qt5ct state=floating rectangle=700x470+0+0 center=on
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Sxiv state=floating
bspc rule -a St:Nmtui rectangle=700x470+0+0 state=floating center=on
bspc rule -a mpv state=floating sticky=on rectangle="$newwidth"x"$newheight"+"$hor"+"$vert"
bspc rule -a Qalculate-gtk state=floating center=on rectangle=700x470+0+0


